# Generated by Django 2.2.6 on 2019-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphical', '0002_auto_20191017_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='calgraphicdata',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
